spring:
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest  
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/   
springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
        title: My Spring Boot API
        description: API for managing products
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        display-request-duration: true
    
management:
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: refresh, bus-refresh
logging:
    config: classpath:logback-spring.xml
application:
  config:
    customer-url: http://localhost:3101/api/v1/customers
    payment-url: http://localhost:3104/api/v1/payments
    product-url: http://localhost:3103/api/v1/products    
