server:
  port: 3101

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realtime?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: naga
    password: naga
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/realtime?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    user: naga
    password: naga
    driver: com.mysql.cj.jdbc.Driver
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.community.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
