server:
  port: 3101
spring:
  flyway:  
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: jdbc:mysql://localhost:3306/realtime?useSSL=false&serverTimezone=UTC
    username: root
    password: Nagababu
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    database-platform:  org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
