server:
  port: 3101
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realtime?useSSL=false
    username: nag
    password: nag
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
