server:
  port: 3101
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realtime?useSSL=false&serverTimezone=UTC
    username: root
    password: Nagababu
    driver-class-name:  com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/realtime?useSSL=false&serverTimezone=UTC
    username: root
    password: Nagababu
    enabled:  false
    baseline-on-migrate: true
    locations:  classpath:db/migration  
  jpa:
    database-platform:  org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
