server:
  port: 3102

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/microservice"
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**
            
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        
        - id: payment-service
           uri: lb://payment-service
           predicates:
             - Path=/api/v1/payments/**
             
        - id: notification-service
           uri: lb://customer-service
           predicates:
             - Path=/api/v1/notifications/**
        
        - id: order-service
           uri: lb://order-service
           predicates:
             - Path=/api/v1/orders/**    
