server:
  port: 3104

spring:
  datasource:
    url: jdbc:mysql://database-1.c3ukuqawg2vu.ap-south-1.rds.amazonaws.com:3306/demo
    username: admin
    password: NgabaB4_
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://database-1.c3ukuqawg2vu.ap-south-1.rds.amazonaws.com:3306/demo
    user: admin
    password: NgabaB4_
    driver: com.mysql.cj.jdbc.Driver
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
logging:
  level:
    org.springframework.cache: DEBUG
    com.realtime: DEBUG        
