server:
  port: 3103
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://54.75.25.153:5432/product
    username: nagababu
    password: nagababu
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:  
    enabled: true
    baseline-on-migrate: true
    locations:  classpath:db/migration
logging:
  level:
    org.flywaydb.core: DEBUG    
