server:
  port: 3103
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: nagababu
    password: nagababu
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:  
    enabled:true
    baseline-on-migrate: true
    locations:  classpath:db/migration
